services:
  postgres:
    image: postgres:14.2-alpine
    container_name: psyness-postgres
    restart: always
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
    ports:
      - '15432:5432'
    volumes:
      - ./dev/db/init.sql:/docker-entrypoint-initdb.d/1-init.sql